"""
AZALPLUS Constants - Type Stubs
Auto-generated by validate_constants.py
"""

from typing import Any, Dict, List, Optional, Union

# Constantes principales
VERSION: str
CONSTANTS: Dict[str, Any]

STATUTS: Dict[str, Any]
TYPES_MOUVEMENT_STOCK: Dict[str, Any]
COULEURS_STATUTS: Dict[str, Any]
TVA: Dict[str, Any]
DEVISES: Dict[str, Any]
UNITES: Dict[str, Any]
CONDITIONS_PAIEMENT: Dict[str, Any]
MODES_PAIEMENT: Dict[str, Any]
FREQUENCES: Dict[str, Any]
CIVILITES: Dict[str, Any]
ROLES: Dict[str, Any]
ACTIONS: Dict[str, Any]
TYPES_CHAMPS: Dict[str, Any]
COLONNES_SYSTEME: Dict[str, Any]
LIMITES: Dict[str, Any]
FORMATS: Dict[str, Any]
MESSAGES: Dict[str, Any]
SYSTEME: Dict[str, Any]
RGPD: Dict[str, Any]
AMORTISSEMENTS: Dict[str, Any]
CATEGORIES_IMMOBILISATIONS: Dict[str, Any]
FORMATS_IMPORT_BANCAIRE: Dict[str, Any]

# Fonctions d'accès
def get(path: str, default: Any = None) -> Any: ...
def get_or_raise(path: str) -> Any: ...
def get_statuts(module: str) -> List[str]: ...
def get_statut_defaut(module: str) -> str: ...
def get_couleur_statut(statut: str) -> str: ...
def get_tva(pays: str = "france", type_tva: str = "normal") -> float: ...
def get_tva_options(pays: str = "france") -> Dict[str, float]: ...
def get_devise(code: str = None) -> Dict[str, Any]: ...
def get_devises_disponibles() -> List[str]: ...
def get_limite(categorie: str, cle: str = None) -> Union[int, Dict[str, Any]]: ...
def get_format(type_format: str, variante: str = "affichage") -> str: ...
def get_message(code: str) -> str: ...
def get_roles() -> Dict[str, Dict[str, Any]]: ...
def get_role(code: str) -> Dict[str, Any]: ...
def get_type_champ(type_yaml: str) -> Dict[str, Any]: ...
def get_colonnes_systeme() -> List[Dict[str, Any]]: ...
def resolve_reference(ref: str) -> Any: ...
def reload_constants() -> None: ...
def validate() -> Dict[str, Any]: ...

# Statuts disponibles
# generiques: BROUILLON, ACTIF, ARCHIVE, ANNULE
# devis: valeurs
# factures: valeurs
# avoirs: valeurs
# paiements: valeurs
# abonnements: valeurs
# projets: valeurs
# chantiers: valeurs
# interventions: valeurs
# tickets: valeurs
# equipements: valeurs
# immobilisations: valeurs
# mouvements_bancaires: valeurs
# conges: valeurs
# consentements: valeurs
# demandes_rgpd: valeurs
# mouvements_stock: valeurs
# stock: valeurs